name: async_redux_project_template
description: A Project template using AsyncRedux for state management.
publish_to: 'none'

version: 3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  async_redux: ^20.0.2
  align_positioned: ^3.0.0
  animated_size_and_fade: ^3.0.1
  animations: ^2.0.7
  assorted_layout_widgets: ^8.0.5
  characters: ^1.3.0
  collection: ^1.17.2
  connectivity: ^3.0.6
  crypto: ^3.0.3
  fast_immutable_collections: ^9.2.0
  flutter_svg: ^2.0.9
  http: ^1.1.0
  i18n_extension: ^9.0.2
  intl: 0.18.1
  matrix4_transform: ^2.0.1
  themed: ^4.0.0
  timezone: ^0.9.2
  weak_map: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
