name: async_redux_project_template
description: A Project template using AsyncRedux for state management.
publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  async_redux: ^19.0.0
  align_positioned: ^3.0.0
  animated_size_and_fade: ^3.0.1
  animations: ^2.0.7
  assorted_layout_widgets: ^7.0.0
  characters: ^1.2.1
  collection: ^1.17.0
  connectivity: ^3.0.6
  crypto: ^3.0.2
  fast_immutable_collections: ^9.0.0
  flutter_svg: ^2.0.2
  http: ^0.13.5
  i18n_extension: ^8.0.0
  intl: 0.17.0
  matrix4_transform: ^2.0.1
  themed: ^4.0.0
  timezone: ^0.9.1
  weak_map: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
